language: c

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode8.3
        - os: linux
          dist: xenial
          sudo: required
          env: BUILD_WINDOWS=yes

git:
  submodules: false

#os:
#    - linux
#    - osx

script:
    - ./travis/build.sh

after_success:
    - ./travis/upload.sh

notifications:
    irc:
        channels:
            - "chat.freenode.net#deadbeefplayer"
        on_success: always
        on_failure: always
        template:
            - "%{branch} - %{commit} : %{author} : %{message}"
            - "Commit message: %{commit_subject}"
            - "Diff: %{compare_url}"
            - "Build details: %{build_url}"
