name: DeaDBeeF Build
on: [ push, pull_request ]
jobs:
  build_linux:
    name: CI for Linux
    runs-on: ubuntu-latest
    container: ubuntu:14.04
    steps:
    - name: Install dependencies for Linux
      run: |
        apt-get -qq update
        apt-get install -y -qq autopoint automake autoconf intltool libc6-dev yasm libglib2.0-bin perl wget zip bzip2 make libtool pkg-config fakeroot clang openssh-client rsync
    - name: Checkout for Linux
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build for Linux
      run: TRAVIS_OS_NAME=linux travis/build.sh
    - name: Upload for Linux
      env:
          gh_rsa_key: ${{ secrets.GH_ENCRYPTED_RSA_KEY }}
          gh_rsa_iv: ${{ secrets.GH_ENCRYPTED_RSA_IV }}
      run: TRAVIS_OS_NAME=linux travis/upload.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: portable_out/build/*.tar.bz2
  build_mac:
    name: CI for macOS
    runs-on: macos-latest
    steps:
    - name: Checkout for macOS
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.4.0'
    - name: Build for macOS
      run: TRAVIS_OS_NAME=osx travis/build.sh
    - name: Upload for macOS
      env:
          gh_rsa_key: ${{ secrets.GH_ENCRYPTED_RSA_KEY }}
          gh_rsa_iv: ${{ secrets.GH_ENCRYPTED_RSA_IV }}
      run: TRAVIS_OS_NAME=osx travis/upload.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mac
        path: osx/build/Release/*.zip
  build_windows:
    name: CI for Windows
    runs-on: windows-latest
    steps:
    - name: Checkout for Windows
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain mingw-w64-x86_64-libzip mingw-w64-x86_64-pkg-config mingw-w64-x86_64-dlfcn
          git make tar unzip xz zip mingw-w64-x86_64-clang mingw-w64-x86_64-libblocksruntime
          mingw-w64-x86_64-jansson mingw-w64-x86_64-gtk3 mingw-w64-x86_64-gtk2 mingw-w64-x86_64-mpg123
          mingw-w64-x86_64-flac mingw-w64-x86_64-curl mingw-w64-x86_64-portaudio mingw-w64-x86_64-faad2 mingw-w64-x86_64-flac
          mingw-w64-x86_64-wavpack mingw-w64-x86_64-libvorbis mingw-w64-x86_64-libogg mingw-w64-x86_64-opusfile mingw-w64-x86_64-opus
          mingw-w64-x86_64-libsndfile mingw-w64-x86_64-libsamplerate mingw-w64-x86_64-yasm rsync
    - name: Build for Windows
      shell: msys2 {0}
      run: TRAVIS_OS_NAME=windows travis/build.sh
    - name: Upload for Windows
      env:
          gh_rsa_key: ${{ secrets.GH_ENCRYPTED_RSA_KEY }}
          gh_rsa_iv: ${{ secrets.GH_ENCRYPTED_RSA_IV }}
      shell: msys2 {0}
      run: TRAVIS_OS_NAME=windows travis/upload.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: bin/*DEBUG.zip
