name: Build for Mac
on: [ push, pull_request ]
jobs:
  build_mac:
    name: CI for macOS
    runs-on: macos-latest
    steps:
    - name: Checkout for macOS
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13'
    - name: Build for macOS
      run: TRAVIS_OS_NAME=osx travis/build.sh
    - name: Upload for macOS
      env:
          gh_ed25519_key: ${{ secrets.GH_ENCRYPTED_ED25519_KEY }}
          gh_ed25519_iv: ${{ secrets.GH_ENCRYPTED_ED25519_IV }}
      run: TRAVIS_OS_NAME=osx travis/upload.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mac
        path: osx/build/Release/*.zip
