name: Mac Release Build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build_mac:
    name: Mac Release Build
    runs-on: macos-latest
    env:
      GITHUB_BUILD_NUMBER: ${{ github.run_number }}
    steps:
    - name: Checkout for macOS
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16'
    - name: Build for macOS
      run: BUILD_OS_NAME=osx ci_scripts/build.sh
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: always()
      with:
        files: |
          osx/build/reports/junit.xml
    - name: Upload for macOS
      env:
        gh_ed25519_key: ${{ secrets.GH_ENCRYPTED_ED25519_KEY }}
        gh_ed25519_iv: ${{ secrets.GH_ENCRYPTED_ED25519_IV }}
      run: BUILD_OS_NAME=osx ci_scripts/upload.sh
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: deadbeef-macos-universal
        path: osx/build/Release/*-universal.zip
        if-no-files-found: error
    - name: Upload debug symbols
      uses: actions/upload-artifact@v4
      with:
        name: deadbeef-macos-dSYM
        path: osx/build/Release/*-dSYM.zip
        if-no-files-found: warn
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: osx/build/Release/*.log
        if-no-files-found: warn
